name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 0.3.1
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.6.0-nullsafety.2
  path_provider: ^2.0.0-nullsafety
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  mockito: ^5.0.0-nullsafety.7
  build_runner: ^1.11.1

